#!/bin/bash
set -o pipefail
output=$(rmcpping -c 5 $1 | tail -1)
code=$?
loss=$(echo $output | grep -oP "([0-9\.]+)(?=% packet loss)")
line="$output | loss=$loss"
if [ "$code" -eq 0 ]; then
        echo "OK - $line"
        exit 0
else
        echo "CRITICAL - $line"
        exit 2
fi
