"""Example config for Icingagen."""
CONFIG_DIR = "/opt/monitoring/config"
ICINGA_URL = "https://icinga.example.com:5665/v1/"
ICINGA_USER = "icingagen"
ICINGA_PASS = "icingagenpass"
ICINGA_CA = "/var/lib/icinga2/certs/ca.crt"
NETBOX_URL = "https://netbox.example.com"
